"""empty message

Revision ID: 148575c03861
Revises: 
Create Date: 2019-05-09 15:41:54.507529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148575c03861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=200), nullable=True, comment='名称'),
    sa.Column('operator', sa.String(length=200), nullable=True, comment='操作人'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('gender', sa.String(length=4), nullable=True, comment='性别'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('avatar', sa.String(length=128), nullable=True, comment='头像'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='生日'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('data_source')
    # ### end Alembic commands ###
