"""empty message

Revision ID: 4a92b9383744
Revises: 798b26ae283d
Create Date: 2019-10-20 21:46:08.447824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a92b9383744'
down_revision = '798b26ae283d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('depart_name', sa.String(length=50), nullable=True))
    op.drop_column('department', 'name')
    op.add_column('permission_y', sa.Column('permi_name', sa.Enum('ADMIN', 'STATION_ADMIN', 'USER', name='permissionenum'), nullable=True))
    op.drop_column('permission_y', 'name')
    op.add_column('station', sa.Column('station_name', sa.String(length=50), nullable=True))
    op.drop_column('station', 'name')
    op.add_column('user_y', sa.Column('account', sa.String(64), nullable=False))
    op.add_column('user_y', sa.Column('user_name', sa.String(length=50), nullable=True))
    op.drop_column('user_y', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_y', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('user_y', 'user_name')
    op.drop_column('user_y', 'account')
    op.add_column('station', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('station', 'station_name')
    op.add_column('permission_y', sa.Column('name', mysql.ENUM('ADMIN', 'STATION_ADMIN', 'USER'), nullable=True))
    op.drop_column('permission_y', 'permi_name')
    op.add_column('department', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('department', 'depart_name')
    # ### end Alembic commands ###
