"""empty message

Revision ID: 93a7a49aed59
Revises: ae248ae78687
Create Date: 2019-05-14 11:07:05.154441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a7a49aed59'
down_revision = 'ae248ae78687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plant', sa.Column('image', sa.String(length=1024), nullable=True, comment='图片'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plant', 'image')
    # ### end Alembic commands ###
