"""empty message

Revision ID: ae248ae78687
Revises: 
Create Date: 2019-05-14 09:44:07.362725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae248ae78687'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=40), nullable=True, comment='名称'),
    sa.Column('category', sa.String(length=40), nullable=True, comment='分类'),
    sa.Column('needs', sa.String(length=40), nullable=True, comment='成长条件'),
    sa.Column('active_flag', sa.Boolean(), server_default=sa.text('True'), nullable=True, comment='是否启用，True启用 False不启用'),
    sa.Column('seed_unit', sa.String(length=4), nullable=True, comment='种子单位'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plant_active_flag'), 'plant', ['active_flag'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('gender', sa.String(length=4), nullable=True, comment='性别'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('avatar', sa.String(length=128), nullable=True, comment='头像'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='生日'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('plant_id', sa.Integer(), nullable=True, comment='植物id'),
    sa.Column('category', sa.String(length=40), nullable=True, comment='分类'),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=True, comment='单位种子价格'),
    sa.Column('unit', sa.String(length=4), nullable=True, comment='种子单位'),
    sa.Column('time_cost', sa.String(length=40), nullable=True, comment='预计所需时间'),
    sa.Column('area_need', sa.Integer(), nullable=True, comment='占地面积'),
    sa.Column('area_unit', sa.String(length=40), nullable=True, comment='占地面积单位'),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('plant_id', sa.Integer(), nullable=True, comment='植物id'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('active_flag', sa.Boolean(), server_default=sa.text('True'), nullable=True, comment='是否启用，True启用 False不启用'),
    sa.Column('water', sa.Integer(), nullable=True, comment='水分'),
    sa.Column('fertilizer', sa.Integer(), nullable=True, comment='肥料'),
    sa.Column('pesticide', sa.Integer(), nullable=True, comment='药'),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=True, comment='价值'),
    sa.Column('harvest_at', sa.Date(), nullable=True, comment='预计收获时间'),
    sa.Column('status', sa.Enum('HEALTHY', 'SICK', 'DEAD', 'THIN', 'DRY', 'RESET', name='plantstatus'), nullable=True, comment='状态'),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_plant_active_flag'), 'user_plant', ['active_flag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_plant_active_flag'), table_name='user_plant')
    op.drop_table('user_plant')
    op.drop_table('seed')
    op.drop_table('user')
    op.drop_index(op.f('ix_plant_active_flag'), table_name='plant')
    op.drop_table('plant')
    # ### end Alembic commands ###
