"""empty message

Revision ID: dd531818ca6d
Revises: 01d8f2d836bf
Create Date: 2019-10-13 10:46:27.057611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd531818ca6d'
down_revision = '01d8f2d836bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=40), nullable=True, comment='名称'),
    sa.Column('category', sa.String(length=40), nullable=True, comment='分类'),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=True, comment='单位价格'),
    sa.Column('unit', sa.String(length=4), nullable=True, comment='单位'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pesticide',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('name', sa.String(length=40), nullable=True, comment='名称'),
    sa.Column('category', sa.String(length=40), nullable=True, comment='分类'),
    sa.Column('price', sa.Numeric(precision=4, scale=2), nullable=True, comment='单位价格'),
    sa.Column('unit', sa.String(length=4), nullable=True, comment='单位'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('storage', sa.Column('item_type', sa.Enum('SEED', 'FERTILIZER', 'PESTICIDE', name='itemtype'), nullable=True, comment='物品类型'))
    op.add_column('storage', sa.Column('quantity', sa.Integer(), nullable=True, comment='数量'))
    op.alter_column('storage', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户id',
               existing_comment='用户',
               existing_nullable=True)
    op.add_column('user', sa.Column('money', sa.Numeric(), nullable=True, comment='XIN'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'money')
    op.alter_column('storage', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户',
               existing_comment='用户id',
               existing_nullable=True)
    op.drop_column('storage', 'quantity')
    op.drop_column('storage', 'item_type')
    op.drop_table('pesticide')
    op.drop_table('fertilizer')
    # ### end Alembic commands ###
