"""empty message

Revision ID: dd589e9b5286
Revises: 
Create Date: 2019-03-19 15:43:06.751077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd589e9b5286'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='修改时间'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='分类名称'),
    sa.Column('valid', sa.Boolean(), nullable=True, comment='有效性'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='修改时间'),
    sa.Column('name', sa.String(length=50), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码'),
    sa.Column('gender', sa.String(length=4), nullable=True, comment='性别'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('email', sa.String(length=50), nullable=True, comment='邮箱'),
    sa.Column('avatar', sa.String(length=128), nullable=True, comment='头像'),
    sa.Column('birthday', sa.Date(), nullable=True, comment='生日'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='修改时间'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='发布者id'),
    sa.Column('title', sa.String(length=50), nullable=True, comment='标题'),
    sa.Column('content', sa.String(length=5000), nullable=True, comment='内容'),
    sa.Column('category', sa.String(length=20), nullable=True, comment='分类'),
    sa.Column('valid', sa.Boolean(), nullable=True, comment='有效性'),
    sa.Column('clicks', sa.Integer(), nullable=True, comment='点击量'),
    sa.Column('likes', sa.Integer(), nullable=True, comment='点赞量'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='修改时间'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户id'),
    sa.Column('content', sa.String(length=200), nullable=True, comment='评论内容'),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='所属内容ID'),
    sa.Column('father_id', sa.Integer(), nullable=True, comment='父评论ID'),
    sa.Column('valid', sa.Boolean(), nullable=True, comment='有效性'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['father_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('article_catalog')
    # ### end Alembic commands ###
